# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{munin_manager}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rohith Ravi"]
  s.date = %q{2009-10-07}
  s.default_executable = %q{munin_manager}
  s.email = %q{entombedvirus@gmail.com}
  s.executables = ["munin_manager"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/munin_manager",
     "bin/runner",
     "lib/munin_manager.rb",
     "lib/munin_manager/acts_as_munin_plugin.rb",
     "lib/munin_manager/log_reader.rb",
     "lib/munin_manager/plugins.rb",
     "lib/munin_manager/plugins/fbproxy_latency.rb",
     "lib/munin_manager/plugins/haproxy_app_response_time.rb",
     "lib/munin_manager/plugins/haproxy_response_time.rb",
     "lib/munin_manager/plugins/haproxy_rps.rb",
     "lib/munin_manager/plugins/network_latency.rb",
     "lib/munin_manager/plugins/notification_classification.rb",
     "lib/munin_manager/plugins/packet_loss.rb",
     "lib/munin_manager/plugins/rails_rendering.rb",
     "lib/munin_manager/plugins/rails_response_time.rb",
     "lib/munin_manager/plugins/scribe_net.rb",
     "lib/munin_manager/plugins/starling_age.rb",
     "lib/munin_manager/plugins/starling_net.rb",
     "lib/munin_manager/plugins/starling_ops.rb",
     "lib/munin_manager/plugins/starling_queue.rb",
     "lib/munin_manager/starling/starling_stats.rb",
     "test/haproxy_response_time_test.rb",
     "test/log_reader_test.rb",
     "test/rails_response_time_test.rb",
     "test/test_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/entombedvirus/jeweler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.2}
  s.summary = %q{Tool to maintain and install munin plugins written in Ruby}
  s.test_files = [
    "test/haproxy_response_time_test.rb",
     "test/log_reader_test.rb",
     "test/rails_response_time_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
